project_id = "xwemjiljadhpvxwhgvid"

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-proposal-notification]
verify_jwt = false

[functions.conditional-signup]
verify_jwt = false